### ISSUE TITLE
Backend will not run 

### ISSUE THREAD

**Issue by shamprasadrh** [episerver/content-graph-js-sdk#34]
Backend does not run due to API Gateway and no instructions on setting up the GateWay to run the sample

`(base) ➜  musicfestival-backend-dotnet git:(main) ✗ dotnet run                                                                                                                            
Building...
Adding OpenID Connect
info: EPiServer.Framework.Initialization.InitializationEngine[0]
      Initialization started
info: EPiServer.Events.EventsInitialization[0]
      No event providers has been configured. Events will not be distributed to other servers.
info: EPiServer.Shell.Modules.ModuleTable[0]
      Adding module CMS
info: EPiServer.Shell.Modules.ModuleTable[0]
      Adding module Shell
info: EPiServer.Shell.Modules.ModuleTable[0]
      Adding module EPiServer.Cms.TinyMce
info: EPiServer.Shell.Modules.ModuleTable[0]
      Adding module EPiServer.Cms.UI.Settings
info: EPiServer.Shell.Modules.ModuleTable[0]
      Adding module Optimizely.ContentGraph.Cms.NetCore
info: EPiServer.Shell.Modules.ModuleTable[0]
      Adding module EPiServer.Cms.UI.VisitorGroups
info: EPiServer.Shell.Modules.ModuleTable[0]
      Adding module EPiServer.Cms.UI.Admin
info: EPiServer.Shell.Modules.ModuleTable[0]
      Adding module EPiServer.OpenIDConnect.UI
info: EPiServer.Shell.Modules.ModuleTable[0]
      Adding module App
info: EPiServer.Shell.Json.Internal.ShellModuleFormatterOptionsConfigurer[0]
      Resolving Json serializer for Module 'EPiServer.Cms.TinyMce' with setting 'ModuleJsonSerializerType=Resolve' and 'PreferredUiJsonSerializerType=Resolve'
info: EPiServer.Shell.Json.Internal.ShellModuleFormatterOptionsConfigurer[0]
      Resolved System.Text.Json serializer for Module 'EPiServer.Cms.TinyMce' according to global formatter
info: EPiServer.Shell.Json.Internal.ShellModuleFormatterOptionsConfigurer[0]
      Resolving Json serializer for Module 'EPiServer.Cms.UI.Settings' with setting 'ModuleJsonSerializerType=Net' and 'PreferredUiJsonSerializerType=Net'
info: EPiServer.Shell.Json.Internal.ShellModuleFormatterOptionsConfigurer[0]
      Resolving Json serializer for Module 'Optimizely.ContentGraph.Cms.NetCore' with setting 'ModuleJsonSerializerType=Net' and 'PreferredUiJsonSerializerType=Resolve'
info: EPiServer.Shell.Json.Internal.ShellModuleFormatterOptionsConfigurer[0]
      Resolving Json serializer for Module 'EPiServer.Cms.UI.VisitorGroups' with setting 'ModuleJsonSerializerType=Net' and 'PreferredUiJsonSerializerType=Net'
info: EPiServer.Shell.Json.Internal.ShellModuleFormatterOptionsConfigurer[0]
      Resolving Json serializer for Module 'EPiServer.Cms.UI.Admin' with setting 'ModuleJsonSerializerType=None' and 'PreferredUiJsonSerializerType=Net'
info: EPiServer.Shell.Json.Internal.ShellModuleFormatterOptionsConfigurer[0]
      Resolving Json serializer for Module 'EPiServer.OpenIDConnect.UI' with setting 'ModuleJsonSerializerType=Resolve' and 'PreferredUiJsonSerializerType=Resolve'
info: EPiServer.Shell.Json.Internal.ShellModuleFormatterOptionsConfigurer[0]
      Resolved System.Text.Json serializer for Module 'EPiServer.OpenIDConnect.UI' according to global formatter
info: EPiServer.Shell.Json.Internal.ShellModuleFormatterOptionsConfigurer[0]
      Resolving Json serializer for Module 'App' with setting 'ModuleJsonSerializerType=Resolve' and 'PreferredUiJsonSerializerType=Resolve'
info: EPiServer.Shell.Json.Internal.ShellModuleFormatterOptionsConfigurer[0]
      Resolved System.Text.Json serializer for Module 'App' according to global formatter
info: EPiServer.Shell.Json.Internal.ShellModuleFormatterOptionsConfigurer[0]
      Resolved System.Text.Json as serializer for CMS UI
info: EPiServer.Framework.Initialization.InitializationEngine[0]
      Initialization completed
info: MusicFestival.Backend.ProvisionDatabase[0]
      Provisioning primary site host.
Unhandled exception. Optimizely.ContentGraph.Core.Connection.ServiceException: Connection refused (localhost:8082)
 ---> System.Net.Http.HttpRequestException: Connection refused (localhost:8082)
 ---> System.Net.Sockets.SocketException (61): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Polly.CircuitBreaker.AsyncCircuitBreakerEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, ExceptionPredicates shouldHandleExceptionPredicates, ResultPredicates`1 shouldHandleResultPredicates, ICircuitController`1 breakerController)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass0_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy`1 outerPolicy, IAsyncPolicy`1 innerPolicy)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass0_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy`1 outerPolicy, IAsyncPolicy`1 innerPolicy)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Optimizely.ContentGraph.Core.Connection.ServiceExceptionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Optimizely.ContentGraph.Core.Connection.ServiceExceptionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at EPiServer.Turnstile.Contracts.Hmac.HmacMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Optimizely.ContentGraph.Core.Client.StreamAsync(IEnumerable`1 operations, CancellationToken cancellationToken)
   at Optimizely.ContentGraph.Cms.Core.Internal.SiteDefinitionIndexer.IndexAsync()
   at Optimizely.ContentGraph.Cms.Core.Internal.EventIndexingInitialization.SyncSiteSettings()
   at Optimizely.ContentGraph.Cms.Core.Internal.EventIndexingInitialization.SiteChange(Object sender, SiteDefinitionEventArgs e)
   at EPiServer.Web.Internal.DefaultSiteDefinitionRepository.Save(SiteDefinition siteDefinition)
   at MusicFestival.Backend.ProvisionDatabase.AddPrimarySiteHost() in /Users/shamprasad/Projects/content-graph-js-sdk/samples/musicfestival-backend-dotnet/ProvisionDatabase.cs:line 56
   at MusicFestival.Backend.ProvisionDatabase.StartAsync(CancellationToken cancellationToken) in /Users/shamprasad/Projects/content-graph-js-sdk/samples/musicfestival-backend-dotnet/ProvisionDatabase.cs:line 20
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at MusicFestival.Backend.Program.Main(String[] args) in /Users/shamprasad/Projects/content-graph-js-sdk/samples/musicfestival-backend-dotnet/Program.cs:line 7`

**Comment by jamestran1** [comment]
the gateway is a SAAS, so you need an account to experience with it, ping @jonasbergqvist
